### ISSUE TITLE
Remove sensitive credential files

### ISSUE THREAD

**Issue by andreas-bauer** [BobLee135/exploro#40]
@FPZKryddan @BobLee135  please delete `app/google-services.json`.  
Credential files should never be commited into the repository. 

Have a look at [GitHub's docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) to see how you can delete in in a proper way from your repository.

**Comment by FPZKryddan** [comment]
Must have missed that one. I have now deleted that file from the current build and throughout the repository history!
